language: java
sudo: required
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  
before_install:
 - chmod +x gradlew
 
 script:
 - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)