language: java
sudo: required
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  
before_install:
 - chmod +x gradlew 
 script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 312054ab-7e9d-4508-9288-b6668799adf7
  